[build]
builder = "nixpacks"
buildCommand = "cd site && npm install && npm run build"
configPath = "site"

[deploy]
startCommand = "cd site && NODE_OPTIONS='--max-old-space-size=400' npm run start"
numReplicas = 1
