import type { Metadata } from "next";
import Image from "next/image";
import { PageHeader } from "@/components/site/PageHeader";
import { Section } from "@/components/ui/Section";
import { Eyebrow } from "@/components/ui/Eyebrow";
import { Button } from "@/components/ui/Button";
import { Reveal } from "@/components/ui/Reveal";

export const metadata: Metadata = {
 title: "Services",
 description:
 "Six services across Fashol's agricultural supply chain platform: farm-to-market, logistics, buyer tools, market intelligence, quality grading, and financial settlement.",
};

const SPECS = [
 ["App", "যোগান · Jogaan · Android"],
 ["Language", "Bengali (primary) · English"],
 ["Users", "60,000+ farmers · 7,000+ buyers · 140 field agents"],
 ["Modules", "06"],
 ["Settlement", "Within 24 h of weigh-in - named bank / bKash"],
 ["Coverage", "9 districts · expanding to 15 in 2026"],
];

const SERVICES = [
 {
 id: "farm-to-market",
 no: "01",
 title: "Farm-to-market platform",
 sub: "Direct matching, farmer to buyer.",
 image: "/images/content/farmer-cabbage.jpg",
 alt: "A registered farmer holding a cabbage in a Fashol.com branded shirt at harvest in the field.",
 body: [
 "The base layer. Farmers register through Jogaan, listing crop, quantity, harvest window, and expected price. Buyers post demand. The platform matches the two directly - no aratdars, no price opacity, no delayed settlement.",
 "Pricing is visible to both sides from the point of agreement. Every transaction is logged against a farmer ID that they own and can show to banks, extension officers, or offtakers outside the platform.",
 ],
 specs: [
 ["Tag", "Fashol · B2B"],
 ["Users", "60,000+ farmers · 7,000+ buyers"],
 ["Coverage", "09 districts, BD"],
 ["Settlement", "Within 24 hours of weighing"],
 ],
 },
 {
 id: "logistics",
 no: "02",
 title: "Smart logistics network",
 sub: "Cold chain where it was never built.",
 image: "/images/content/warehouse.jpg",
 alt: "A cold-storage warehouse interior with orange racking and goods stacked in aisles.",
 body: [
 "Last-mile pickup and cold-chain dispatch serve forty-plus district hubs, many of them in climate-vulnerable coastal and riverine belts that had no prior cold-chain infrastructure.",
 "Route plans are generated by the platform and executed by company fleet and partner operators. Temperature and dwell-time are logged against each crate so a buyer knows how long a kilo of tomato has been out of cold before it reached them.",
 ],
 specs: [
 ["Tag", "Fleet · Route"],
 ["Hubs", "40+ distribution hubs"],
 ["Waste", "−26% vs. traditional route"],
 ["Partners", "DITECH (perishables)"],
 ],
 },
 {
 id: "buyer-solutions",
 no: "03",
 title: "Buyer solutions",
 sub: "Ordering, inventory, and fulfilment for four buyer classes.",
 image: "/images/content/market-women.jpg",
 alt: "Women selling fresh vegetables at a subcontinental market.",
 body: [
 "Buyers - MSMEs, quick-commerce operators, exporters, wholesalers - use a tailored ordering interface with live inventory, tier-graded produce, and delivery-window visibility.",
 "Bulk and recurring orders are supported. Foodpanda, Chaldal, Daraz, and Domino's are among the 7,000+ buyer accounts currently on the platform.",
 ],
 specs: [
 ["Tag", "SaaS · Retail"],
 ["Classes", "MSME / Quick commerce / Export / Wholesale"],
 ["Known buyers", "Foodpanda, Chaldal, Daraz, Domino's, US-Bangla"],
 ["SLA", "Same-day & next-day windows"],
 ],
 },
 {
 id: "market-intelligence",
 no: "04",
 title: "Market intelligence",
 sub: "Real-time pricing, made available to the grower.",
 image: "/images/content/market-aerial-bd.jpg",
 alt: "Aerial view of a bustling outdoor vegetable market in rural Bangladesh.",
 body: [
 "The same price signals that commodity desks and urban wholesalers rely on - published daily to the Jogaan app in Bengali, with a seven-day trailing chart and a twelve-month seasonal comparison.",
 "The audience is smallholder growers in climate-vulnerable districts for whom a day-late price signal is a week-late planting decision.",
 ],
 specs: [
 ["Tag", "Data · Pricing"],
 ["Update", "Daily, every mandi"],
 ["Languages", "Bengali (primary), English"],
 ["Published", "Jogaan app · SMS alerts"],
 ],
 },
 {
 id: "quality-assurance",
 no: "05",
 title: "Quality assurance",
 sub: "A four-tier grade applied at hub intake.",
 image: "/images/content/farmer-watering.jpg",
 alt: "A farmer waters eggplant crops in a field at daylight.",
 body: [
 "Produce is graded on weight, visual defect, storage-life, and provenance before it leaves the district. The tier is set at the hub, not at the urban wholesale market - which is the common practice elsewhere and the origin of most adulteration.",
 "Grade A goes to exporters and quick commerce; Grade B to MSMEs; Grade C to wholesale; Grade D is rejected and routed to animal feed or compost contractors.",
 ],
 specs: [
 ["Tag", "Grade · QC"],
 ["Tiers", "A / B / C / D"],
 ["Applied", "At hub intake, before dispatch"],
 ["Audit", "Quarterly, third-party"],
 ],
 },
 {
 id: "financial-solvency",
 no: "06",
 title: "Financial solvency",
 sub: "Twenty-four-hour settlement. Credit against a registered track record.",
 image: "/images/content/farmer-sowing.jpg",
 alt: "A farmer in an orange shirt sowing seed in a paddy field.",
 body: [
 "Farmers are paid through mobile financial services (upay, bKash, Nagad) within 24 hours of weighing - against a traditional 2-to-6-week cycle elsewhere in the chain.",
 "Farmers with a twelve-month track record on the platform qualify for seasonal credit from banking partners, underwritten against their registered volumes rather than their land.",
 ],
 specs: [
 ["Tag", "Payments · Credit"],
 ["Rails", "upay · bKash · Nagad"],
 ["Banking", "Dutch-Bangla Bank (settlement)"],
 ["Cycle", "≤24 hours from weighing"],
 ],
 },
];

export default function ServicesPage() {
 return (
 <><PageHeader
 eyebrow="যোগান Jogaan"
 title={<>The platform <em>is</em> an app in the farmer&apos;s hand.</>}
 lede={
 <>
 Every Fashol service - onboarding, pricing, collection, grading, settlement, and order book - runs through
 <em> Jogaan</em>, the Bengali-first Android app our field agents carry and our farmers receive a notification
 from at 19:00 each evening. The six modules below are the work that sits behind the app.
 </>
 }
 />

 {/* Specs + Jogaan screens */}
 <Section tone="surface" size="sm">
 <div className="grid desktop:grid-cols-12 gap-10 items-start">
 <div className="desktop:col-span-5">
 <div className="grid grid-cols-1 gap-y-5">
 {SPECS.map(([k, v]) => (
 <div key={k} className="border-t border-[var(--color-line)] pt-3 flex justify-between gap-4">
 <span className="t-mono text-[11px] text-[var(--color-ink-muted)] shrink-0">{k}</span>
 <span className="t-body-sm text-right">{v}</span>
 </div>
 ))}
 </div>
 </div>

 <div className="desktop:col-span-7 grid grid-cols-3 gap-4">
 {["jogaan-1", "jogaan-2", "jogaan-3"].map((s, i) => (
 <div key={s} className="relative aspect-[9/16] rounded-3xl overflow-hidden border border-[var(--color-line)] bg-white shadow-[var(--shadow-layered)]">
 <Image
 src={`/images/content/${s}.png`}
 alt={["Jogaan app - farmer registration screen, Bengali-first.", "Jogaan app - next-day offer price and collection slot.", "Jogaan app - settlement confirmation and payout."][i]}
 fill
 sizes="(min-width: 1200px) 240px, 30vw"
 className="object-cover"
 />
 </div>
 ))}
 </div>
 </div>
 <p className="mt-8 t-caption">
 Three Jogaan screens, left to right: onboarding, next-day offer, settlement.
 </p>
 </Section>

 {/* Services */}
 <Section tone="paper">
 <Reveal as="h2" delay={0.08} className="t-h2 mt-6 max-w-3xl">Each module below runs in production today.</Reveal>

 <div className="mt-20 space-y-20 desktop:space-y-28">
 {SERVICES.map((s, i) => {
 const flip = i % 2 === 1;
 return (
 <div key={s.id} id={s.id} className="grid desktop:grid-cols-12 gap-10 items-start scroll-mt-28">
 <Reveal className={`desktop:col-span-6 ${flip ? "desktop:order-2" : ""}`}>
 <div className="relative aspect-[4/5] rounded-3xl overflow-hidden">
 <Image src={s.image} alt={s.alt} fill sizes="(min-width: 1200px) 560px, 90vw" className="object-cover" />
 </div>
 </Reveal>
 <div className="desktop:col-span-6">
 <Reveal>
 <div className="flex items-baseline gap-4">
 <span className="t-mono text-[11px] text-[var(--color-terracotta)]">{s.no}</span>
 <Eyebrow>Service {s.no}</Eyebrow>
 </div>
 <h3 className="t-h3 mt-4">{s.title}</h3>
 <p className="t-h5 mt-4 !text-[var(--color-ink-subtle)]" style={{ fontWeight: 400 }}>{s.sub}</p>
 </Reveal>
 <Reveal delay={0.08} className="mt-8 space-y-4 t-body">
 {s.body.map((p, j) => <p key={j}>{p}</p>)}
 </Reveal>
 <Reveal delay={0.16} className="mt-8 grid grid-cols-2 gap-y-4">
 {s.specs.map(([k, v]) => (
 <div key={k} className="border-t border-[var(--color-line)] pt-3">
 <div className="t-mono text-[11px] text-[var(--color-ink-muted)]">{k}</div>
 <div className="t-body-sm mt-1">{v}</div>
 </div>
 ))}
 </Reveal>
 </div>
 </div>
 );
 })}
 </div>
 </Section>

 {/* Jogaan panel */}
 <Section tone="ink">
 <div className="grid desktop:grid-cols-12 gap-10 items-center">
 <div className="desktop:col-span-7">
 <h2 className="t-h2 mt-6 max-w-2xl">
 <span className="lang-bn">যোগান</span> - Jogaan. The app the field runs on.
 </h2>
 <p className="t-body-lg !text-[rgba(255,255,255,0.75)] mt-6 max-w-2xl">
 Bengali verb meaning &ldquo;to supply.&rdquo; Built for field agents and farmers who handle registration, price lock,
 collection, and payment on one device.
 </p>
 <p className="t-body-lg !text-[rgba(255,255,255,0.75)] mt-4">
 Available on Google Play for Android 7.0+. Full Bengali localisation; English optional. Field-tested with agents
 and farmers who have never used a smartphone before.
 </p>
 <div className="mt-8 grid grid-cols-2 tablet:grid-cols-4 gap-6 t-mono text-[11px] !text-[rgba(255,255,255,0.7)]">
 <div><div>Platform</div><div className="text-white mt-1">Android 7.0+</div></div>
 <div><div>Audience</div><div className="text-white mt-1">Agents · farmers</div></div>
 <div><div>Languages</div><div className="text-white mt-1">Bengali · English</div></div>
 <div><div>Version</div><div className="text-white mt-1">v 3.2 · 2026.02</div></div>
 </div>
 <div className="mt-10">
 <Button variant="primary" href="https://play.google.com/store/apps/details?id=com.fashol.agent" external>
 Install on Google Play
 </Button>
 </div>
 </div>
 <div className="desktop:col-span-5 relative aspect-[9/16] max-w-sm mx-auto w-full">
 <Image
 src="/images/content/jogaan-2.png"
 alt="Jogaan app - pricing and collection screen."
 fill
 sizes="(min-width: 1200px) 380px, 80vw"
 className="object-cover rounded-3xl border border-[rgba(255,255,255,0.15)]"
 />
 </div>
 </div>
 </Section>

 {/* Onboard CTA triad */}
 <Section tone="surface">
 <Reveal as="h2" className="t-h2 mt-6 max-w-3xl">Start with one service. Or all six.</Reveal>
 <div className="grid tablet:grid-cols-3 gap-6 mt-14">
 {[
 { n: "01", t: "Register as farmer", b: "Bring your last season's records. WhatsApp a field agent.", href: "https://wa.me/+8801810187230?text=Hello!%20I%E2%80%99d%20like%20to%20register%20as%20a%20farmer%20with%20Fashol." },
 { n: "02", t: "Open a buyer account", b: "MSME, QC, exporter, wholesale - 10-minute set-up.", href: "https://wa.me/+8801810187230?text=Hello!%20I%E2%80%99d%20like%20to%20open%20a%20buyer%20account%20with%20Fashol." },
 { n: "03", t: "Integration & partnerships", b: "Logistics, cold chain, financial rails, NGO partners.", href: "/contact" },
 ].map((c) => (
 <div key={c.n} className="card-plain p-8 flex flex-col gap-4">
 <span className="t-mono text-[11px] text-[var(--color-terracotta)]">{c.n}</span>
 <h3 className="t-h4" style={{ fontWeight: 500 }}>{c.t}</h3>
 <p className="t-body">{c.b}</p>
 <div className="mt-auto pt-4">
 <Button variant="primary" href={c.href} external={c.href.startsWith("http")}>Continue</Button>
 </div>
 </div>
 ))}
 </div>
 </Section>
 </>
 );
}
